create table category (
                          category_id int generated by default as identity primary key,
                          name varchar (1000),
                          add_date timestamp not null,
                          mod_date timestamp not null
);