create table category (
                          category_id int generated by default as identity primary key,
                          category_name varchar (1000) unique,
                          add_date timestamp not null,
                          mod_date timestamp not null
);