create table topic (
                       topic_id int generated by default as identity primary key,
                       topic_name varchar(200) not null,
                       category_id int not null,
                       doc_adddate timestamp not null,
                       doc_moddate timestamp not null,
                       foreign key (category_id) references category(category_id)
);