create table question (
    question_id int generated by default as identity primary key,
    question_name varchar(2000) not null,
    topic_id int not null,
    doc_adddate timestamp not null,
    doc_moddate timestamp not null,
    foreign key (topic_id) references topic(topic_id)
);