create table answer (
    answer_id int generated by default as identity primary key,
    answer_name varchar(5000) not null,
    question_id int not null,
    doc_adddate timestamp not null,
    doc_moddate timestamp not null,
    foreign key (question_id) references question(question_id)
);